#!/bin/bash
set -e

# Configuration
TARGET_DIR="docs/visuals"
FILENAME="agrinexus-dashboard-enhanced.png"
TARGET_PATH="${TARGET_DIR}/${FILENAME}"

echo "📸 Dashboard Screenshot Setup"
echo "================================"
echo ""
echo "The screenshot you provided shows the enhanced CloudWatch dashboard."
echo "To save it to the repository:"
echo ""
echo "Option 1: Manual Save (Recommended)"
echo "  1. Right-click on the screenshot image you provided"
echo "  2. Select 'Save Image As...'"
echo "  3. Save to: ${TARGET_PATH}"
echo ""
echo "Option 2: Take Fresh Screenshot"
echo "  1. Open: https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=AgriNexus-Enhanced-Dashboard-dev"
echo "  2. Set time range: 'Last 7 days'"
echo "  3. Click 'Actions' → 'View in full screen'"
echo "  4. Take screenshot: Cmd+Shift+4 (Mac) or Win+Shift+S (Windows)"
echo "  5. Save to: ${TARGET_PATH}"
echo ""
echo "After saving the image, run:"
echo "  git add ${TARGET_PATH}"
echo "  git commit -m 'Add enhanced CloudWatch dashboard screenshot'"
echo ""
echo "Target location: ${TARGET_PATH}"
echo "Directory exists: $([ -d "${TARGET_DIR}" ] && echo "✅ Yes" || echo "❌ No")"
echo ""
