version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "agrinexus-dev"
s3_prefix = "agrinexus-dev"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=dev"
confirm_changeset = true
resolve_s3 = true

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "agrinexus-prod"
s3_prefix = "agrinexus-prod"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=prod"
confirm_changeset = true
resolve_s3 = true
