version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "agrinexus-week2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-skxuyk7b5ott"
s3_prefix = "agrinexus-week2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "Environment=dev",
    "TableName=agrinexus-data",
    "KnowledgeBaseId=H81XLD3YWY",
    "GuardrailId=\"\"",
    "GuardrailVersion=1"
]

[default.build]
[default.build.parameters]
cached = true
parallel = true
