AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AgriNexus AI - Week 1 Foundation (DynamoDB + Bedrock KB + Guardrails)

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME: !Ref AgriNexusTable
        KNOWLEDGE_BASE_ID: !GetAtt BedrockKnowledgeBase.KnowledgeBaseId
        GUARDRAIL_ID: !GetAtt BedrockGuardrail.GuardrailId
        GUARDRAIL_VERSION: !GetAtt BedrockGuardrail.Version

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

Resources:
  # ============================================================================
  # DynamoDB Single Table Design
  # ============================================================================
  AgriNexusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: agrinexus-data
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Project
          Value: AgriNexus
        - Key: Environment
          Value: !Ref Environment

  # ============================================================================
  # S3 Bucket for Knowledge Base PDFs
  # ============================================================================
  KnowledgeBaseBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub agrinexus-kb-${AWS::AccountId}-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      Tags:
        - Key: Project
          Value: AgriNexus
        - Key: Environment
          Value: !Ref Environment

  # ============================================================================
  # Bedrock Knowledge Base IAM Role
  # ============================================================================
  BedrockKBRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub AgriNexus-BedrockKB-Role-${Environment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
              ArnLike:
                aws:SourceArn: !Sub arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:knowledge-base/*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt KnowledgeBaseBucket.Arn
                  - !Sub ${KnowledgeBaseBucket.Arn}/*

  # ============================================================================
  # Bedrock Knowledge Base (using default managed vector store)
  # ============================================================================
  BedrockKnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    DependsOn:
      - BedrockKBRole
      - KnowledgeBaseBucket
    Properties:
      Name: agrinexus-fao-kb
      Description: FAO agricultural manuals for AgriNexus AI (Hindi, Marathi, Telugu responses from English sources)
      RoleArn: !GetAtt BedrockKBRole.Arn
      KnowledgeBaseConfiguration:
        Type: VECTOR
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.titan-embed-text-v1
      StorageConfiguration:
        Type: OPENSEARCH_SERVERLESS
        OpensearchServerlessConfiguration:
          CollectionArn: !GetAtt OpenSearchCollection.Arn
          VectorIndexName: agrinexus-index
          FieldMapping:
            VectorField: vector
            TextField: text
            MetadataField: metadata

  # ============================================================================
  # OpenSearch Serverless Collection for Vector Store
  # COST WARNING: OpenSearch Serverless has a minimum cost of ~$20/month
  # (1 OCU for indexing + 1 OCU for search at $0.24/hour each)
  # This is unavoidable when using Bedrock Knowledge Bases with OpenSearch
  # Alternative: Aurora Serverless v2 (requires custom vector store implementation)
  # ============================================================================
  OpenSearchCollection:
    Type: AWS::OpenSearchServerless::Collection
    DependsOn:
      - OpenSearchSecurityPolicy
      - OpenSearchNetworkPolicy
      - OpenSearchDataAccessPolicy
    Properties:
      Name: agrinexus-vectors
      Type: VECTORSEARCH
      Description: Vector store for AgriNexus Knowledge Base

  OpenSearchSecurityPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: agrinexus-security-policy
      Type: encryption
      Policy: !Sub |
        {
          "Rules": [
            {
              "ResourceType": "collection",
              "Resource": ["collection/agrinexus-vectors"]
            }
          ],
          "AWSOwnedKey": true
        }

  OpenSearchNetworkPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: agrinexus-network-policy
      Type: network
      Policy: !Sub |
        [
          {
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": ["collection/agrinexus-vectors"]
              }
            ],
            "AllowFromPublic": true
          }
        ]

  OpenSearchDataAccessPolicy:
    Type: AWS::OpenSearchServerless::AccessPolicy
    Properties:
      Name: agrinexus-data-access-policy
      Type: data
      Policy: !Sub |
        [
          {
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": ["collection/agrinexus-vectors"],
                "Permission": [
                  "aoss:CreateCollectionItems",
                  "aoss:DeleteCollectionItems",
                  "aoss:UpdateCollectionItems",
                  "aoss:DescribeCollectionItems"
                ]
              },
              {
                "ResourceType": "index",
                "Resource": ["index/agrinexus-vectors/*"],
                "Permission": [
                  "aoss:CreateIndex",
                  "aoss:DeleteIndex",
                  "aoss:UpdateIndex",
                  "aoss:DescribeIndex",
                  "aoss:ReadDocument",
                  "aoss:WriteDocument"
                ]
              }
            ],
            "Principal": [
              "${BedrockKBRole.Arn}",
              "arn:aws:iam::${AWS::AccountId}:root"
            ]
          }
        ]

  # ============================================================================
  # Bedrock Data Source (S3)
  # ============================================================================
  BedrockDataSource:
    Type: AWS::Bedrock::DataSource
    Properties:
      Name: fao-manuals-s3
      Description: FAO PDF manuals from S3
      KnowledgeBaseId: !Ref BedrockKnowledgeBase
      DataSourceConfiguration:
        Type: S3
        S3Configuration:
          BucketArn: !GetAtt KnowledgeBaseBucket.Arn
          InclusionPrefixes:
            - en/

  # ============================================================================
  # Bedrock Guardrails
  # ============================================================================
  BedrockGuardrail:
    Type: AWS::Bedrock::Guardrail
    Properties:
      Name: agrinexus-safety-guardrail
      Description: Blocks banned pesticides, medical advice, and escalates to KVK
      BlockedInputMessaging: "I cannot provide advice on that topic. Please contact your local Krishi Vigyan Kendra (KVK) for assistance."
      BlockedOutputsMessaging: "I cannot provide that information. Please consult your local KVK extension officer."
      ContentPolicyConfig:
        FiltersConfig:
          - Type: HATE
            InputStrength: HIGH
            OutputStrength: HIGH
          - Type: VIOLENCE
            InputStrength: MEDIUM
            OutputStrength: MEDIUM
      WordPolicyConfig:
        WordsConfig:
          - Text: paraquat
          - Text: monocrotophos
          - Text: endosulfan
          - Text: methyl parathion
          - Text: phorate
        ManagedWordListsConfig:
          - Type: PROFANITY
      TopicPolicyConfig:
        TopicsConfig:
          - Name: MedicalAdvice
            Definition: Medical advice, human health diagnosis, or treatment recommendations
            Examples:
              - "What medicine should I take for fever?"
              - "How to treat skin rash?"
            Type: DENY
          - Name: FinancialAdvice
            Definition: Loan recommendations, investment advice, or financial planning
            Examples:
              - "Which bank loan should I take?"
              - "How to invest my money?"
            Type: DENY
      SensitiveInformationPolicyConfig:
        PiiEntitiesConfig:
          - Type: PHONE
            Action: ANONYMIZE
          - Type: EMAIL
            Action: ANONYMIZE

Outputs:
  TableName:
    Description: DynamoDB table name
    Value: !Ref AgriNexusTable
    Export:
      Name: !Sub ${AWS::StackName}-TableName

  TableArn:
    Description: DynamoDB table ARN
    Value: !GetAtt AgriNexusTable.Arn
    Export:
      Name: !Sub ${AWS::StackName}-TableArn

  TableStreamArn:
    Description: DynamoDB Stream ARN
    Value: !GetAtt AgriNexusTable.StreamArn
    Export:
      Name: !Sub ${AWS::StackName}-TableStreamArn

  KnowledgeBaseBucketName:
    Description: S3 bucket for FAO PDFs
    Value: !Ref KnowledgeBaseBucket
    Export:
      Name: !Sub ${AWS::StackName}-KBBucket

  KnowledgeBaseId:
    Description: Bedrock Knowledge Base ID
    Value: !GetAtt BedrockKnowledgeBase.KnowledgeBaseId
    Export:
      Name: !Sub ${AWS::StackName}-KBId

  GuardrailId:
    Description: Bedrock Guardrail ID
    Value: !GetAtt BedrockGuardrail.GuardrailId
    Export:
      Name: !Sub ${AWS::StackName}-GuardrailId

  GuardrailVersion:
    Description: Bedrock Guardrail Version
    Value: !GetAtt BedrockGuardrail.Version
    Export:
      Name: !Sub ${AWS::StackName}-GuardrailVersion
